sudo: required
language: generic
services:
 - docker
env:
  matrix:
   - HHVM_VERSION=3.25.3
   - HHVM_VERSION=3.26.0
   - HHVM_VERSION=latest
   - HHVM_VERSION=nightly
install:
 - docker pull hhvm/hhvm:$HHVM_VERSION
script:
 - env | egrep '^(HHVM_VERSION|GITHUB_API_KEY|TRAVIS_EVENT_TYPE)=' > ./env-list
 - docker run --env-file ./env-list -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION /var/source/.travis.sh
